### ISSUE TITLE
Can we access the .json file from local??

### ISSUE THREAD

**Issue by LokeshD01-dev** [dinohorvat/swagger-editor-angular8#2]
I see the below code in app.component.ts. Is there any way to send the local file path in place of URL?

ngOnInit(): void {
    const editor = SwaggerEditorBundle({
      dom_id: '#swagger-editor',
      layout: 'StandaloneLayout',
      presets: [
        SwaggerEditorStandalonePreset
      ],
      url: 'http://rackerlabs.github.io/wadl2swagger/openstack/swagger/dbaas.json'
    });
  }

**Comment by dinohorvat** [comment]
> I see the below code in app.component.ts. Is there any way to send the local file path in place of URL?
> 
> ngOnInit(): void {
> const editor = SwaggerEditorBundle({
> dom_id: '#swagger-editor',
> layout: 'StandaloneLayout',
> presets: [
> SwaggerEditorStandalonePreset
> ],
> url: 'http://rackerlabs.github.io/wadl2swagger/openstack/swagger/dbaas.json'
> });
> }

I haven't tried it but it should work. Make sure to try it with absolute path though. If it doesn't work, you can always run the apache or nginx server (which I assume you will do in production), and then paste that path.

**Comment by LokeshD01-dev** [comment]
Thanks @dinohorvat . I have one scenario where I need to pass data(JSON) rather than json URL. 
Is it feasible to do so?

Reason behind that is am fetching json data from AWS s3 service. Thanks for the support
